# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'BeeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeeApp
  pod 'Alamofire', '~> 5.2'
  pod 'YZClasses', '~> 0.1.6'
  pod 'KDCircularProgress'
  pod 'IQKeyboardManagerSwift'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'PhoneNumberKit'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'RSKImageCropper'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crashlytics'
  pod 'Socket.IO-Client-Swift', '~> 16.0.1'
#  pod 'YZLibraries', '~> 0.2.1'
end
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#    end
#  end
#end
